export const API_ENDPOINTS = {
  ADS: '/ads',
  CARS: '/cars',
  USERS: '/Users',
  CURENT_USER: '/currentUser',
  SIGNUP: '/signup',
  LOGIN: '/login',
  PHONE_VERIFICATION: '/phone-verfication',
  EMAIL_VERIFICATION: '/email-verfication',
  GOOGLE_AUTH: '/google-auth',
  LOGIN_WITH_EMAIL: '/login-email',
  LOGIN_WITH_MOBILE: '/login-phone',
  SIGNUP_WITH_EMAIL: '/signup-email',
  SIGNUP_WITH_MOBILE: '/signup-phone',
  FORGOT_PASSWORD: '/forgotPassword',
  RESET_PASSWORD: '/resetPassword',
  MARK_SOLD:"/mark-sold",
  MARK_UNSOLD:"/mark-unsold",
  MARK_ACTIVE:"/mark-active",
  MARK_INACTIVE:"/mark-inactive",
  CAR_MAKES:"/makes",
  MAKE_MODELS:"/models/?make_id=",
  MODEL_VERSIONS:"/versions?model_id=",
};
